-- ------------------------- info -------------------------
-- @@ver: 1_000_000
-- @@info: 初始化fa-disk模块
-- ------------------------- info -------------------------

-- ----------------------------
-- Table structure for disk_store_bucket
-- ----------------------------

CREATE TABLE IF NOT EXISTS "disk_store_bucket" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "size" bigint DEFAULT NULL,
  "dir_count" integer DEFAULT NULL,
  "file_count" integer DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "disk_store_bucket" IS 'STORE-库';
COMMENT ON COLUMN "disk_store_bucket"."id" IS 'ID';
COMMENT ON COLUMN "disk_store_bucket"."name" IS '库名称';
COMMENT ON COLUMN "disk_store_bucket"."size" IS '总文件大小';
COMMENT ON COLUMN "disk_store_bucket"."dir_count" IS '目录数量';
COMMENT ON COLUMN "disk_store_bucket"."file_count" IS '文件数量';
COMMENT ON COLUMN "disk_store_bucket"."crt_time" IS '创建时间';
COMMENT ON COLUMN "disk_store_bucket"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "disk_store_bucket"."crt_name" IS '创建用户';
COMMENT ON COLUMN "disk_store_bucket"."crt_host" IS '创建IP';
COMMENT ON COLUMN "disk_store_bucket"."upd_time" IS '更新时间';
COMMENT ON COLUMN "disk_store_bucket"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "disk_store_bucket"."upd_name" IS '更新用户';
COMMENT ON COLUMN "disk_store_bucket"."upd_host" IS '更新IP';
COMMENT ON COLUMN "disk_store_bucket"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "disk_store_bucket__upd_time" ON "disk_store_bucket";
CREATE TRIGGER "disk_store_bucket__upd_time" BEFORE UPDATE ON "disk_store_bucket" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for disk_store_bucket_user
-- ----------------------------

CREATE TABLE IF NOT EXISTS "disk_store_bucket_user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bucket_id" integer NOT NULL,
  "user_id" varchar(32) NOT NULL,
  "type" smallint NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "disk_store_bucket_user" IS 'STORE-库-人员关联';
COMMENT ON COLUMN "disk_store_bucket_user"."id" IS 'ID';
COMMENT ON COLUMN "disk_store_bucket_user"."bucket_id" IS '库ID';
COMMENT ON COLUMN "disk_store_bucket_user"."user_id" IS '用户ID';
COMMENT ON COLUMN "disk_store_bucket_user"."type" IS '类型1-创建者/2-操作者';
COMMENT ON COLUMN "disk_store_bucket_user"."crt_time" IS '创建时间';
COMMENT ON COLUMN "disk_store_bucket_user"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "disk_store_bucket_user"."crt_name" IS '创建用户';
COMMENT ON COLUMN "disk_store_bucket_user"."crt_host" IS '创建IP';
COMMENT ON COLUMN "disk_store_bucket_user"."upd_time" IS '更新时间';
COMMENT ON COLUMN "disk_store_bucket_user"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "disk_store_bucket_user"."upd_name" IS '更新用户';
COMMENT ON COLUMN "disk_store_bucket_user"."upd_host" IS '更新IP';
COMMENT ON COLUMN "disk_store_bucket_user"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "disk_store_bucket_user__upd_time" ON "disk_store_bucket_user";
CREATE TRIGGER "disk_store_bucket_user__upd_time" BEFORE UPDATE ON "disk_store_bucket_user" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for disk_store_file
-- ----------------------------

CREATE TABLE IF NOT EXISTS "disk_store_file" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bucket_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "parent_id" integer NOT NULL,
  "sort" integer DEFAULT NULL,
  "dir" boolean DEFAULT NULL,
  "size" integer DEFAULT NULL,
  "type" varchar(255) DEFAULT NULL,
  "file_id" varchar(64) DEFAULT NULL,
  "full_path" varchar(1000) DEFAULT NULL,
  "tags" jsonb DEFAULT NULL,
  "info" varchar(255) DEFAULT NULL,
  "delete_action" boolean DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "disk_store_file" IS 'STORE-文件夹';
COMMENT ON COLUMN "disk_store_file"."id" IS 'ID';
COMMENT ON COLUMN "disk_store_file"."bucket_id" IS '库ID';
COMMENT ON COLUMN "disk_store_file"."name" IS '文件夹名称';
COMMENT ON COLUMN "disk_store_file"."parent_id" IS '父级节点';
COMMENT ON COLUMN "disk_store_file"."sort" IS '排序ID';
COMMENT ON COLUMN "disk_store_file"."dir" IS '是否文件夹';
COMMENT ON COLUMN "disk_store_file"."size" IS '文件大小(目录下文件数量/KB)';
COMMENT ON COLUMN "disk_store_file"."type" IS '文件类型';
COMMENT ON COLUMN "disk_store_file"."file_id" IS '文件ID';
COMMENT ON COLUMN "disk_store_file"."full_path" IS '完整路径#dir#,#dir#';
COMMENT ON COLUMN "disk_store_file"."tags" IS '标签';
COMMENT ON COLUMN "disk_store_file"."info" IS '文件信息';
COMMENT ON COLUMN "disk_store_file"."delete_action" IS '是否有删除动作';
COMMENT ON COLUMN "disk_store_file"."crt_time" IS '创建时间';
COMMENT ON COLUMN "disk_store_file"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "disk_store_file"."crt_name" IS '创建用户';
COMMENT ON COLUMN "disk_store_file"."crt_host" IS '创建IP';
COMMENT ON COLUMN "disk_store_file"."upd_time" IS '更新时间';
COMMENT ON COLUMN "disk_store_file"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "disk_store_file"."upd_name" IS '更新用户';
COMMENT ON COLUMN "disk_store_file"."upd_host" IS '更新IP';
COMMENT ON COLUMN "disk_store_file"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "disk_store_file__upd_time" ON "disk_store_file";
CREATE TRIGGER "disk_store_file__upd_time" BEFORE UPDATE ON "disk_store_file" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for disk_store_file_tag
-- ----------------------------

CREATE TABLE IF NOT EXISTS "disk_store_file_tag" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "file_id" integer NOT NULL,
  "tag_id" integer NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "disk_store_file_tag" IS 'STORE-文件-标签';
COMMENT ON COLUMN "disk_store_file_tag"."id" IS 'ID';
COMMENT ON COLUMN "disk_store_file_tag"."file_id" IS '文件ID';
COMMENT ON COLUMN "disk_store_file_tag"."tag_id" IS '标签ID';
COMMENT ON COLUMN "disk_store_file_tag"."crt_time" IS '创建时间';
COMMENT ON COLUMN "disk_store_file_tag"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "disk_store_file_tag"."crt_name" IS '创建用户';
COMMENT ON COLUMN "disk_store_file_tag"."crt_host" IS '创建IP';
COMMENT ON COLUMN "disk_store_file_tag"."upd_time" IS '更新时间';
COMMENT ON COLUMN "disk_store_file_tag"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "disk_store_file_tag"."upd_name" IS '更新用户';
COMMENT ON COLUMN "disk_store_file_tag"."upd_host" IS '更新IP';
COMMENT ON COLUMN "disk_store_file_tag"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "disk_store_file_tag__upd_time" ON "disk_store_file_tag";
CREATE TRIGGER "disk_store_file_tag__upd_time" BEFORE UPDATE ON "disk_store_file_tag" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for disk_store_tag
-- ----------------------------

CREATE TABLE IF NOT EXISTS "disk_store_tag" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bucket_id" integer NOT NULL,
  "parent_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "sort" integer NOT NULL,
  "color" varchar(10) NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "disk_store_tag" IS 'STORE-标签';
COMMENT ON COLUMN "disk_store_tag"."id" IS 'ID';
COMMENT ON COLUMN "disk_store_tag"."bucket_id" IS '库ID';
COMMENT ON COLUMN "disk_store_tag"."parent_id" IS '父ID';
COMMENT ON COLUMN "disk_store_tag"."name" IS '名称';
COMMENT ON COLUMN "disk_store_tag"."sort" IS '排序ID';
COMMENT ON COLUMN "disk_store_tag"."color" IS '颜色';
COMMENT ON COLUMN "disk_store_tag"."crt_time" IS '创建时间';
COMMENT ON COLUMN "disk_store_tag"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "disk_store_tag"."crt_name" IS '创建用户';
COMMENT ON COLUMN "disk_store_tag"."crt_host" IS '创建IP';
COMMENT ON COLUMN "disk_store_tag"."upd_time" IS '更新时间';
COMMENT ON COLUMN "disk_store_tag"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "disk_store_tag"."upd_name" IS '更新用户';
COMMENT ON COLUMN "disk_store_tag"."upd_host" IS '更新IP';
COMMENT ON COLUMN "disk_store_tag"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "disk_store_tag__upd_time" ON "disk_store_tag";
CREATE TRIGGER "disk_store_tag__upd_time" BEFORE UPDATE ON "disk_store_tag" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Records of base_job
-- ----------------------------
BEGIN;
INSERT INTO "base_job" ("id", "job_name", "cron", "status", "clazz_path", "job_desc", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (2, '[网盘][文件库]同步文件库信息', '0 0/1 * * * ?', TRUE, 'com.faber.api.disk.store.jobs.JobSyncBucketInfo', NULL, '2022-12-30 16:33:47', '1', '超级管理员', '127.0.0.1', '2022-12-30 16:34:10', '1', '超级管理员', '127.0.0.1', FALSE);
COMMIT;

-- ----------------------------
-- Records of base_rbac_menu
-- ----------------------------
BEGIN;
INSERT INTO "base_rbac_menu" ("id", "parent_id", "name", "sort", "level", "icon", "status", "link_type", "link_url", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (22000000, 0, '文档管理', 2, 0, 'floppy-disk', TRUE, 1, '/admin/disk', '2022-12-22 09:48:01', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE);
INSERT INTO "base_rbac_menu" ("id", "parent_id", "name", "sort", "level", "icon", "status", "link_type", "link_url", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (22010000, 22000000, '文件仓库', 0, 1, 'store', TRUE, 1, '/admin/disk/buckets', '2022-12-23 10:23:29', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE);
INSERT INTO "base_rbac_menu" ("id", "parent_id", "name", "sort", "level", "icon", "status", "link_type", "link_url", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (22020000, 22000000, '文件网盘', 1, 1, 'laptop-file', TRUE, 1, '/admin/disk/store', '2022-12-22 09:49:00', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE);
COMMIT;

SELECT setval(
    pg_get_serial_sequence('base_rbac_menu', 'id'),
    COALESCE((SELECT MAX("id") FROM "base_rbac_menu"), 1),
    TRUE
);

SELECT setval(
    pg_get_serial_sequence('base_job', 'id'),
    COALESCE((SELECT MAX("id") FROM "base_job"), 1),
    TRUE
);

