-- ------------------------- info -------------------------
-- @@ver: 1_000_001
-- @@info: 新增文档历史记录表
-- ------------------------- info -------------------------

-- ----------------------------
-- Table structure for disk_store_bucket
-- ----------------------------

CREATE TABLE IF NOT EXISTS "disk_store_file_his" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "store_file_id" integer NOT NULL,
    "file_save_id" varchar(32) NOT NULL,
    "file_name" varchar(255) NOT NULL,
    "remark" text NULL,
    "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "crt_user" varchar(32) NOT NULL,
    "crt_name" varchar(255) NOT NULL,
    "crt_host" varchar(255) NULL DEFAULT NULL,
    "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    "upd_user" varchar(32) NULL DEFAULT NULL,
    "upd_name" varchar(255) NULL DEFAULT NULL,
    "upd_host" varchar(255) NULL DEFAULT NULL,
    "deleted" boolean NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE "disk_store_file_his" IS 'STORE-文件-历史记录';
COMMENT ON COLUMN "disk_store_file_his"."id" IS 'ID';
COMMENT ON COLUMN "disk_store_file_his"."store_file_id" IS '存储文件ID';
COMMENT ON COLUMN "disk_store_file_his"."file_save_id" IS '版本文件ID';
COMMENT ON COLUMN "disk_store_file_his"."file_name" IS '文件名';
COMMENT ON COLUMN "disk_store_file_his"."remark" IS '备注';
COMMENT ON COLUMN "disk_store_file_his"."crt_time" IS '创建时间';
COMMENT ON COLUMN "disk_store_file_his"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "disk_store_file_his"."crt_name" IS '创建用户';
COMMENT ON COLUMN "disk_store_file_his"."crt_host" IS '创建IP';
COMMENT ON COLUMN "disk_store_file_his"."upd_time" IS '更新时间';
COMMENT ON COLUMN "disk_store_file_his"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "disk_store_file_his"."upd_name" IS '更新用户';
COMMENT ON COLUMN "disk_store_file_his"."upd_host" IS '更新IP';
COMMENT ON COLUMN "disk_store_file_his"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "disk_store_file_his__upd_time" ON "disk_store_file_his";
CREATE TRIGGER "disk_store_file_his__upd_time" BEFORE UPDATE ON "disk_store_file_his" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

